# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


SYSTEMS = ["Xbox", "Playstation", "Nintendo", "PC", "Application", "Trading Card Game"]
XBOX_GAMES = [
  "Battalion 1944",
  "Battlerite",
  "Brawlhalla",
  "Brawlout",
  "Call of Duty: Black Ops 4",
  "Capcom vs. SNK 2",
  "Catherine",
  "Counter Strike: Global Offensive",
  "Deformers",
  "DRAGON BALL FighterZ",
  "FIFA",
  "For Honor",
  "Fortnite",
  "Forza",
  "Gears of War 4",
  "Gwent",
  "Halo",
  "Halo 2",
  "Halo 3",
  "Halo 4",
  "Halo 5",
  "Halo: Reach",
  "Injustice 2",
  "Killer Instinct",
  "Killer Instinct 2",
  "Lethal League",
  "Lethal League Blaze",
  "Madden NFL",
  "Marvel vs. Capcom: Infinite",
  "Mortal Kombat 9",
  "Mortal Kombat X",
  "NBA 2K",
  "NBA Live",
  "NHL",
  "Overcooked",
  "Overwatch",
  "Paladins: Champions of the Realm",
  "PUBG",
  "Rainbow Six Siege",
  "Realm Royale",
  "Rivals of Aether",
  "Rocket League",
  "SNK Heroines",
  "Soulcalibur V",
  "Soulcalibur VI",
  "Street Fighter 30th Anniversary Collection",
  "Street Fighter III: 3rd Strike",
  "Street Fighter IV",
  "Team Fortress 2",
  "Tekken 7",
  "UFC",
  "Ultimate Marvel vs. Capcom 3",
  "Ultra Street Fighter IV",
  "WWE",
  ]
PLAYSTATION_GAMES = [
  "Battalion 1944",
  "Blade Strangers",
  "BlazBlue: Central Fiction",
  "BlazBlue: Cross Tag Battle",
  "Brawlout",
  "Counter Strike: Global Offensive",
  "Call of Duty: Black Ops 4",
  "Brawlhalla",
  "Catherine",
  "Capcom vs. SNK 2",
  "DRAGON BALL FighterZ",
  "Deformers",
  "Disc Jam",
  "FIFA",
  "Fighting EX Layer",
  "For Honor",
  "Fortnite",
  "Guilty Gear Xrd",
  "Guilty Gear Xrd REV2",
  "Gwent",
  "Injustice 2",
  "Gundam Versus",
  "Lawbreakers",
  "Lethal League",
  "Rocket League",
  "Lethal League Blaze",
  "MLB The Show ",
  "Madden NFL",
  "Marvel vs. Capcom: Infinite",
  "Mortal Kombat 9",
  "Mortal Kombat X",
  "NBA 2K",
  "NBA Live",
  "NHL",
  "Overcooked",
  "Overwatch",
  "Paladins: Champions of the Realm",
  "Raw Data",
  "Team Fortress 2",
  "Realm Royale",
  "Soulcalibur V",
  "Street Fighter V",
  "Soulcalibur VI",
  "Skullgirls: 2nd Encore",
  "Space Pirate Trainer",
  "Street Fighter 30th Anniversary Collection",
  "Street Fighter III: 3rd Strike",
  "Street Fighter IV",
  "Tekken 7",
  "Super Street Fighter II Turbo",
  "The King of Fighters XIV",
  "Rainbow Six Siege",
  "Tooth and Tail",
  "UFC",
  "Ultimate Marvel vs. Capcom 3",
  "Ultra Street Fighter IV",
  "Under Night In-Birth",
  "Vampire Savior",
  "Windjammers",
  "WWE",
  ]
NINTENDO_GAMES = [
  "Arms",
  "Blade Strangers",
  "BlazBlue: Central Fiction",
  "BlazBlue: Cross Tag Battle",
  "Brawlhalla",
  "Brawlout",
  "Capcom vs. SNK 2",
  "Disc Jam",
  "DRAGON BALL FighterZ",
  "FIFA",
  "Fortnite",
  "Killer Queen",
  "Mario Kart 64",
  "Mario Kart 7",
  "Mario Kart 8",
  "Mario Kart Double Dash",
  "Mario Kart Wii",
  "Mario Party",
  "Mario Party 10",
  "Mario Party 2",
  "Mario Party 3",
  "Mario Party 8",
  "Mario Party 9",
  "Mario Tennis Aces",
  "NBA 2K",
  "Overcooked",
  "Paladins: Champions of the Realm",
  "Pokemon Sun & Moon",
  "Pokemon VGC",
  "Pokkén Tournament",
  "Rocket Leage",
  "Skullgirls: 2nd Encore",
  "SNK Heroines",
  "Splatoon",
  "Splatoon 2",
  "Street Fighter 30th Anniversary Collection",
  "Super Mario Party",
  "Super Smash Bros 64",
  "Super Smash Bros Brawl",
  "Super Smash Bros Melee",
  "Super Smash Bros Project M",
  "Super Smash Bros Ultimate",
  "Super Smash Bros Wii U",
  "Windjammers",
  "WWE",
  ]
PC_GAMES = [
  "Age of Empires 1",
  "Age of Empires 2",
  "Age of Empires 3",
  "Age of Empires 4",
  "Battalion 1944",
  "Battlerite",
  "Blade Strangers",
  "BlazBlue: Central Fiction",
  "BlazBlue: Cross Tag Battle",
  "Brawlhalla",
  "Brawlout",
  "Call of Duty: Black Ops 4",
  "Counter Strike: Global Offensive",
  "Cube 2: Sauerbraten",
  "Deformers",
  "Dimensions VS",
  "Disc Jam",
  "Dissidia Final Fantasy NT",
  "Dota 2",
  "DRAGON BALL FighterZ",
  "Duelyst",
  "FIFA",
  "Fight of Gods",
  "Fighting EX Layer",
  "For Honor",
  "Fortnite",
  "Forza",
  "Gears of War 4",
  "Guilty Gear Xrd",
  "Guilty Gear Xrd REV2",
  "Gwent",
  "Hearthstone",
  "Heroes of the Storm",
  "Icons: Combat Arena",
  "Indie Pogo",
  "Injustice 2",
  "Ironsight",
  "Killer Instinct",
  "Killer Instinct 2",
  "Killer Queen",
  "Lawbreakers",
  "League of Legends",
  "Lethal League",
  "Lethal League Blaze",
  "Madden NFL",
  "Marvel vs. Capcom: Infinite",
  "Midair",
  "Mortal Kombat 9",
  "Mortal Kombat X",
  "Overcooked",
  "Overwatch",
  "Paladins: Champions of the Realm",
  "Pokemon Showdown",
  "PUBG",
  "Puyo Puyo VS2",
  "Quake Champions",
  "Rainbow Six Siege",
  "Raw Data",
  "Realm Royale",
  "Ring Of Elysium",
  "Rivals of Aether",
  "Rocket League",
  "Roof Rage",
  "Slap City",
  "Smite",
  "Soulcalibur VI",
  "Splitgate: Arena Warfare",
  "Starcraft II",
  "StarCraft: Brood War",
  "Street Fighter 30th Anniversary Collection",
  "Street Fighter 5",
  "Street Fighter IV",
  "Team Fortress 2",
  "Tekken 7",
  "The King of Fighters XIV",
  "Them's Fightin' Herds",
  "Tooth and Tail",
  "Ultimate Marvel vs. Capcom 3",
  "Ultra Street Fighter II",
  "Ultra Street Fighter IV",
  "Under Night In-Birth",
  "WWE",
  ]
APPLICATION_GAMES = [
  "Hearthstone",
  "Vainglory",
  "Clash Royale",
  "Dragon Ball Legends"
]
TCG_GAMES = [
  "Bakugan",
  "Beyblade",
  "Cardfight!! Vanguard",
  "Chaotic",
  "Digimon",
  "Digimon Fusion",
  "Dragon Ball Z",
  "Duel Masters",
  "Future Card Buddyfight",
  "Harry Potter Trading Card Game",
  "Hearthstone",
  "Legend of the Five Rings",
  "Lord Of The Rings TCG",
  "Magic The Gathering",
  "Naruto",
  "Netrunner",
  "Pokémon TCG",
  "Shadowfist",
  "Star Wars",
  "Sword Girls",
  "Vampire: The Eternal Struggle",
  "VS System Marvel",
  "Walking Dead",
  "World Of Warcraft TCG",
  "Yu-Gi-Oh",
  "Yu-Gi-Oh 5D's",
  "Yu-Gi-Oh Arc-V",
  ]

SYSTEMS.each{|s| System.create!(name: s)}

_xbox = System.find_by(name: "Xbox")
_play = System.find_by(name: "Playstation")
_nint = System.find_by(name: "Nintendo")
_pc = System.find_by(name: "PC")
_app = System.find_by(name: "Application")
_tcg = System.find_by(name: "Trading Card Game")

XBOX_GAMES.each{|g| Game.create!(name: g, system_id: _xbox.id)}
PLAYSTATION_GAMES.each{|g| Game.create!(name: g, system_id: _play.id)}
NINTENDO_GAMES.each{|g| Game.create!(name: g, system_id: _nint.id)}
PC_GAMES.each{|g| Game.create!(name: g, system_id: _pc.id)}
APPLICATION_GAMES.each{|g| Game.create!(name: g, system_id: _app.id)}
TCG_GAMES.each{|g| Game.create!(name: g, system_id: _tcg.id)}
